name: clairvoyantenv

channels:
  - conda-forge

dependencies:
  # Python (pipeline)
  - python=3.11
  - pip
  - numpy
  - pandas
  - yfinance

  #  R (visuals + time series)
  - r-base>=4.3
  - r-tidyverse        # includes ggplot2, dplyr, tidyr, readr, etc.
  - r-tidyquant        # tq_get for market data
  - r-zoo              # rollapply
  - r-ggcorrplot
  - r-ggally
  - r-scales
  - r-lubridate

   #  pip packages 
  - pip:
      - requests-cache